### ISSUE TITLE
Problem starting nmonvisualizer via Xwindows

### ISSUE THREAD

**Issue by rowswell** [nmonvisualizer/nmonvisualizer#105] opened 2024-04-03 19:57 UTC
Hi - I am using AIX, Java and Common Desktop Environment/X11 with VNC. 

# java -version
java version "1.8.0_361"
Java(TM) SE Runtime Environment (build 8.0.8.0 - pap6480sr8-20230314_01(SR8))
IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20230313_47323 (JIT enabled, AOT enabled)
OpenJ9   - 4d03a8c
OMR      - 49526cb
IBM      - 7187a01)
JCL - 20230208_01 based on Oracle jdk8u361-b09

# java -jar NMONVisualizer_2024-02-29.jar
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: java/awt/Toolkit.getMenuShortcutKeyMaskEx()I (loaded from /usr/java8_64/jre/lib/rt.jar by <Bootstrap Loader>) called from class com.ibm.nmon.gui.main.MainMenu (loaded from file:/root/NMONVisualizer_2024-02-29.jar by sun.misc.Launcher$AppClassLoader@f8f256e5).
        at com.ibm.nmon.gui.main.MainMenu.createFileMenu(MainMenu.java:84)
        at com.ibm.nmon.gui.main.MainMenu.<init>(MainMenu.java:65)
        at com.ibm.nmon.gui.main.NMONVisualizerGui.<init>(NMONVisualizerGui.java:173)
        at com.ibm.nmon.gui.main.NMONVisualizerGui$1.run(NMONVisualizerGui.java:77)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:322)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:769)
        at java.awt.EventQueue.access$500(EventQueue.java:108)
        at java.awt.EventQueue$3.run(EventQueue.java:720)
        at java.awt.EventQueue$3.run(EventQueue.java:714)
        at java.security.AccessController.doPrivileged(AccessController.java:717)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:739)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:216)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:127)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:112)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:104)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:93)

Any idea?
Thanks
Dean

**Comment by hpresnall** [comment] 2024-04-03 23:23
I think this is a duplicate of #104 
Can you run with Java 11?

**Comment by rowswell** [comment] 2024-04-04 19:12
Hi Hunter - yes that was it - thanks!

I installed "ibm-semeru-certified-11-jre-11.0.22.0-1.ppc64.rpm" and the NMON Visualizer GUI is working fine now with X11/VNC.

Dean

**Closed** 2024-04-04 19:14 UTC
