### ISSUE TITLE
macOS High Sierra and Java 9 (probably only Java 9 issue)

### ISSUE THREAD

**Issue by michaello1** [nmonvisualizer/nmonvisualizer#48] opened 2017-12-18 12:06 UTC
Hi,

when I try to start NMONVisualizer on macOS High Sierra with Java 9 it ends up with:
`java -jar NMONVisualizer_2017-08-08.jar 
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.ibm.nmon.NMONVisualizerApp.<init>(NMONVisualizerApp.java:40)
	at com.ibm.nmon.gui.main.NMONVisualizerGui.<init>(NMONVisualizerGui.java:122)
	at com.ibm.nmon.gui.main.NMONVisualizerGui$1.run(NMONVisualizerGui.java:72)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 17 more
`

It is probably an issue with Java 9 and jarinjarloader you use. Some references:
  - [https://stackoverflow.com/questions/47527410/java9-causes-classnotfoundexception-for-class-in-packaged-library](url)
  - [https://stackoverflow.com/questions/43606502/how-to-add-a-java-9-module-via-manifest-mf(url)

Java version:
`java --version
java 9.0.1
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)`

**Comment by hpresnall** [comment] 2017-12-18 15:38
Confirmed with Oracle JVM on Windows.

Can you please try and build the latest commit and let me know if it works?
I updated the jar-in-jar loader to the latest version and it works on Windows. However, I had to no-op the JSON parser due to classloader errors. I need to track that down with Jackson.

**Comment by hpresnall** [comment] 2017-12-18 18:34
Looks like all the errors can be fixed by dropping the jar-in-jar loader completely. Please try the latest commit.

**Comment by michaello1** [comment] 2017-12-18 22:27
Works on macOS as well. Thanks for very quick resolution :-). My workaround for this issue was moving embedded jar files out of the jar and run the NMONVisualiser with:
`java -cp 'NMONVisualizer_2017-08-08.jar:./*' com.ibm.nmon.DelegatingMain`

**Closed** 2017-12-20 18:08 UTC
